<?php

/**
 * ActualiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActualiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActualiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Actualite');
    }
}