<?php

/**
 * Partenaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Partenaire extends BasePartenaire
{
    /**
     *addPromotion
     * @param Promotion $promotion
     */
    public function addPromotion(Promotion $promotion)
    {
        $promotion->partenaire_id = $this->id;
        $promotion->save();
    }

    /**
     *getPromotions
     * @return Doctrine_Collection
     */
    public function getPromotions()
    {
        $query = Doctrine_Query::create()
            ->from('Promotion p')
            ->where('p.partenaire_id = :pid', array(':pid' => $this->id));
        return $query->execute();
    }
}